### PR TITLE
Implemented resume command

### PR DESCRIPTION
**Pull request by zealot128**
I've added a first version of the "gtt resume" command.

When working on a project and have to switch contexts, like fixing a bug in another project, then returning to the original work, this commands "resume" the tracking.

```bash
cd project1/
gtt start SOME_ISSUE
# ...do work

# get interrupted for urgent bug fix
gtt stop
cd project2/
gtt create "fixing bug"
# fixing bug...
gtt stop

# returning to project
cd project1
gtt resume
```

This is a first version of the command, I may have not considered all usecases. Instead editing/reoping the original entry, a new edit is created. Please comment on the code, where you like to do something else or throw it away entirely :)

I like to use a .gtt.yml file per project, so specifying the --project parameter via commandline is not necessary for me, as that is assumed from the config. If the user does not have a .gtt.yml, the last entry will be recontinued. Also useful for breaks, etc.

### CODE REVIEW

**Comment by kriskbx** [comment]
This is a cool and very useful idea. I really appreciate your contribution. Just gimme some time to look into it and try it out. :)

**Comment by kriskbx** [comment]
I merged your PR but did some refactoring so the code looks a bit cleaner. Thank you so much for your contribution, I really appreciate it. I will release a new version of gtt containing this feature within the next few days.

**Comment by zealot128** [comment]
that's great. Thanks for the making this project :)

**Comment by kriskbx** [comment]
You're welcome. :)

**Pull request merged**
